site_name: FRC Team 1246 Docs
repo_url: https://github.com/AgincourtSkunkworks/FRCDocs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.ico
  language: en
  palette:
    scheme: slate
    primary: black
    accent: grey
  features:
    - content.code.copy  # adds a copy button to code blocks
    - content.code.annotate  # allows annotation in code blocks
    - content.tooltips  # improved title attributes (tooltips)
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    - navigation.expand  # automatically expands all collapsible sections in the ToC
    - navigation.footer  # adds previous/next buttons to the bottom of the page for easier navigation
    - navigation.indexes  # allows for the specification of an index for sections, either `index.md` in the folder, or specified in the `nav` config
    - navigation.path  # shows breadcrumbs above the title (insiders only, doesn't do anything)
    - navigation.tabs  # enables navigation tabs (renders top-level sections as tabs on the navbar rather than in the ToC)
    - search.share  # adds a share button (and support for shared links) to search queries
extra:
  social:  # add social links to the footer (https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links)
    - icon: fontawesome/brands/github
      link: https://github.com/AgincourtSkunkworks
  # NOTE: To anyone looking to remove the generator notice ("Made with Material for MkDocs"), this was INTENTIONALLY
  #       left ENABLED when the docs site was initially made to support the Material for MkDocs project. Please consider
  #       leaving it enabled. See: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
  - git-revision-date-localized:  # shows revision dates at the bottom of the document
      enabled: !ENV [CI, false]
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:  # shows the commiters (contributors) to each page at the bottom of the document
      enabled: !ENV [CI, false]
      repository: AgincourtSkunkworks/FRCDocs
      branch: master  # branch to pull from, should be the branch used to deploy the docs
  - mkdocs-nav-weight  # adds support for weighted navigation via frontmatter, allowing for reorganization without manually specifying everything (`nav` config) - https://pypi.org/project/mkdocs-nav-weight/
  - open-in-new-tab  # specifies that all links should be opened in a new tab
  - search  # adds a search bar in the header
  - tags  # adds support for tags (https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
  - toc:  # adds a table of contents to each page, and adds a button to get the anchor link for each section
      title: Table of Contents
      permalink: true
      permalink_title: Jump to Section
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#emoji
  - pymdownx.emoji:  # adds support for various emojis, required/heavily used
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.tabbed:  # adds support for tabbed content in Markdown
      alternate_style: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md  # auto-add abbreviations masterlist
  - abbr  # adds abbreviations (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#abbreviations)
  - admonition  # adds admonitions (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition)
  - attr_list  # allows for HTML & CSS attributes to be added to Markdown, required/heavily used (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists)
  - footnotes  # adds footnotes (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes)
  - md_in_html  # allows for Markdown to be used in HTML segments (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html)
  - pymdownx.details  # allows for collapsible admonitions (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details)
  - pymdownx.highlight  # adds additional highlighting support (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight)
  - pymdownx.inlinehilite  # allows for syntax highlighting in in-line code blocks (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite)
  - pymdownx.keys  # allows for better rendering of keyboard keys (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#keys)
  - pymdownx.superfences  # allows for better nesting of various Markdown elements (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences)
  - tables  # allows for easy Markdown tables (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables)
watch:  # list of non-docs folders that will trigger refresh of mkdocs serve
  - includes
